services:
  comedor_api:
    build:
      context: ./comedor_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: comedor_api
    restart: unless-stopped
    ports:
      - "80:8080"

  usuarios_api:
    build:
      context: ./usuarios_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: usuarios_api
    restart: unless-stopped
    ports:
      - "81:8080"